/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import utils.Util;

/**
 *
 * @author iband
 */
public class FrCadUsuario extends javax.swing.JDialog {

  /**
   * Creates new form FrCadUsuario
   */
  public FrCadUsuario(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlPrincipal = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblNome = new javax.swing.JLabel();
    lblEmail = new javax.swing.JLabel();
    lblSenha = new javax.swing.JLabel();
    lblDataNascimento = new javax.swing.JLabel();
    btnSalvar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jPasswordField1 = new javax.swing.JPasswordField();
    jFormattedTextField1 = new javax.swing.JFormattedTextField();
    chkAtivo = new javax.swing.JCheckBox();
    imgTitulo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastro de Usuário - Projeto POO");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    pnlPrincipal.setBackground(new java.awt.Color(102, 255, 102));
    pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lblTitulo.setText("Cadastro de Usuário");
    pnlPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

    lblNome.setText("Nome");
    pnlPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

    lblEmail.setText("E-mail");
    pnlPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

    lblSenha.setText("Senha");
    pnlPrincipal.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

    lblDataNascimento.setText("Data Nascimento");
    pnlPrincipal.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

    btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
    btnSalvar.setText("Salvar");
    pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 350, 130, -1));

    btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
    btnCancelar.setText("Cancelar");
    pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, -1));
    pnlPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, -1));
    pnlPrincipal.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));
    pnlPrincipal.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));
    pnlPrincipal.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, -1));

    jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
    pnlPrincipal.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, 120, -1));

    chkAtivo.setText("Ativo");
    pnlPrincipal.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

    imgTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
    pnlPrincipal.add(imgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setIconImage(Util.getIcone());
  }//GEN-LAST:event_formWindowOpened

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrCadUsuario dialog = new FrCadUsuario(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnSalvar;
  private javax.swing.JCheckBox chkAtivo;
  private javax.swing.JLabel imgTitulo;
  private javax.swing.JFormattedTextField jFormattedTextField1;
  private javax.swing.JPasswordField jPasswordField1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JLabel lblDataNascimento;
  private javax.swing.JLabel lblEmail;
  private javax.swing.JLabel lblNome;
  private javax.swing.JLabel lblSenha;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables
}
