/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.Util;

/**
 *
 * @author iband
 */
public class FrCadUsuario extends javax.swing.JDialog {

  /**
   * Creates new form FrCadUsuario
   */
  public FrCadUsuario(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlPrincipal = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    lblNome = new javax.swing.JLabel();
    lblEmail = new javax.swing.JLabel();
    lblSenha = new javax.swing.JLabel();
    lblDataNascimento = new javax.swing.JLabel();
    btnSalvar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    edtEmail = new javax.swing.JTextField();
    edtNome = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    edtSenha = new javax.swing.JPasswordField();
    edtDataNascimento = new javax.swing.JFormattedTextField();
    chkAtivo = new javax.swing.JCheckBox();
    imgTitulo = new javax.swing.JLabel();
    lblConfirmeSenha = new javax.swing.JLabel();
    edtConfirmeSenha = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastro de Usuário - Projeto POO");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    pnlPrincipal.setBackground(new java.awt.Color(102, 255, 102));
    pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lblTitulo.setText("Cadastro de Usuário");
    pnlPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

    lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblNome.setText("Nome");
    pnlPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

    lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblEmail.setText("E-mail");
    pnlPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

    lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblSenha.setText("Senha");
    pnlPrincipal.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

    lblDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblDataNascimento.setText("Data Nascimento");
    pnlPrincipal.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

    btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
    btnSalvar.setText("Salvar");
    btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnSalvarMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 130, -1));

    btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
    btnCancelar.setText("Cancelar");
    btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnCancelarMouseClicked(evt);
      }
    });
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });
    pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, -1));

    edtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    pnlPrincipal.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, -1));

    edtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    pnlPrincipal.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));
    pnlPrincipal.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

    edtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    pnlPrincipal.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, -1));

    edtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
    edtDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    pnlPrincipal.add(edtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));

    chkAtivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    chkAtivo.setText("Ativo");
    pnlPrincipal.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

    imgTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
    pnlPrincipal.add(imgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    lblConfirmeSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    lblConfirmeSenha.setText("Confirme a senha");
    pnlPrincipal.add(lblConfirmeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

    edtConfirmeSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    pnlPrincipal.add(edtConfirmeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 250, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setIconImage(Util.getIcone());
  }//GEN-LAST:event_formWindowOpened

  private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
    this.dispose();
  }//GEN-LAST:event_btnCancelarMouseClicked

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
    gravar();
  }//GEN-LAST:event_btnSalvarMouseClicked

  private void gravar(){
    //validar o preenchimento dos campos
    if(!verificarCampos()){
      return;
    }
    
    //ler os campos e guardar num objeto
    Usuario usu = new Usuario();
    usu.setNome(edtNome.getText()); 
    usu.setEmail(edtEmail.getText());
    usu.setSenha(Util.calcularHash(new String(edtSenha.getPassword())));
    usu.setDataNascimento(Util.converterStringToDate(edtDataNascimento.getText()));    
    usu.setAtivo(chkAtivo.isSelected());
    
    //enviar para o banco de dados
    UsuarioController controller = new UsuarioController();
    if(controller.inserir(usu)){
      JOptionPane.showMessageDialog(null, "Usuário inserido");
      this.dispose();
    }
  }
  
  private boolean verificarCampos(){
    if(edtNome.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "Campo 'Nome' em branco");
      return false;
    }
    if(edtEmail.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "Campo 'E-mail' em branco");
      return false;
    }
    if(new String(edtSenha.getPassword()).isEmpty()){
      JOptionPane.showMessageDialog(null, "Campo 'Senha' em branco");
      return false;
    }
    //^ - Início de linha
    //$ - final de linha
    //[] - conjunto de caracteres
    //+ - quantidade de vezes que o conjunto pode aparecer
    //+ - 1 ou mais vezes
    //* - 0 ou mais vezes
    //{5} - 5 vezes
    //{2} - 2 vezes
    if (!edtNome.getText().matches("^[\\p{L} ]+$")) {//a- [a-zA-Z]
      JOptionPane.showMessageDialog(null,
              "O campo 'Nome' possui formato inválido");
      return false;
    }
    if (!edtEmail.getText().matches("^[a-z0-9_.]+@[a-z0-9_.]+.[a-z]+$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Email' possui formato inválido");
      return false;
    }
    if (!edtDataNascimento.getText().matches("^[0-9]{2}/[0-9]{2}/[0-9]{4}$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Data Nascimento' possui formato inválido");
      return false;
    }
    if(new String(edtSenha.getPassword()).length() < 6){
      JOptionPane.showMessageDialog(null,
              "A senha deve ser maior que 6 dígitos");
      return false;
    }
    
    String senha = new String(edtSenha.getPassword());
    String confirmaSenha = new String(edtConfirmeSenha.getPassword());
    if(!senha.equals(confirmaSenha)){
      JOptionPane.showMessageDialog(null,
              "As senhas devem ser iguais");
      return false;
    }
    
    return true;
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrCadUsuario dialog = new FrCadUsuario(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnSalvar;
  private javax.swing.JCheckBox chkAtivo;
  private javax.swing.JPasswordField edtConfirmeSenha;
  private javax.swing.JFormattedTextField edtDataNascimento;
  private javax.swing.JTextField edtEmail;
  private javax.swing.JTextField edtNome;
  private javax.swing.JPasswordField edtSenha;
  private javax.swing.JLabel imgTitulo;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JLabel lblConfirmeSenha;
  private javax.swing.JLabel lblDataNascimento;
  private javax.swing.JLabel lblEmail;
  private javax.swing.JLabel lblNome;
  private javax.swing.JLabel lblSenha;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables
}
