/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import model.UsuarioLogado;
import utils.Util;

/**
 *
 * @author iband
 */
public class FrCadastro extends javax.swing.JDialog {

  /**
   * Creates new form FrCadastro
   */
  public FrCadastro(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    pnlPrincipal = new javax.swing.JPanel();
    lblUsuario = new javax.swing.JLabel();
    edtUsuario = new javax.swing.JTextField();
    btnBuscarUsuario = new javax.swing.JButton();
    edtCodUsuario = new javax.swing.JTextField();
    lblTitulo = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblGrade = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    btnGravarLista = new javax.swing.JButton();
    btnUsuarioLogado = new javax.swing.JButton();

    jButton1.setText("jButton1");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    lblUsuario.setText("Usuário");

    edtUsuario.setEditable(false);

    btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
    btnBuscarUsuario.setText("Procurar");
    btnBuscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnBuscarUsuarioMouseClicked(evt);
      }
    });

    edtCodUsuario.setEditable(false);

    lblTitulo.setText("Exemplo de buscar dados de usuário de outra tela");

    tblGrade.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "Codigo", "Nome", "Selecionado"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, true
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tblGrade);

    jLabel1.setText("Exemplo marcar opções numa grade");

    btnGravarLista.setText("Gravar Lista");
    btnGravarLista.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnGravarListaMouseClicked(evt);
      }
    });

    btnUsuarioLogado.setText("Usu Logado");
    btnUsuarioLogado.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnUsuarioLogadoMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
    pnlPrincipal.setLayout(pnlPrincipalLayout);
    pnlPrincipalLayout.setHorizontalGroup(
      pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlPrincipalLayout.createSequentialGroup()
        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlPrincipalLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(lblTitulo))
          .addGroup(pnlPrincipalLayout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(edtCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lblUsuario)
                  .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addComponent(edtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnBuscarUsuario))
                  .addComponent(jLabel1)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addComponent(btnUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravarLista)))))
        .addContainerGap(41, Short.MAX_VALUE))
    );
    pnlPrincipalLayout.setVerticalGroup(
      pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlPrincipalLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTitulo)
        .addGap(31, 31, 31)
        .addComponent(lblUsuario)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(edtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscarUsuario)
          .addComponent(edtCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGravarLista)
          .addComponent(btnUsuarioLogado))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnBuscarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioMouseClicked
    FrPreencherCombo telaCombo = new FrPreencherCombo(null, rootPaneCheckingEnabled);
    telaCombo.setVisible(true);
    Usuario usuarioSelecionado = telaCombo.getUsuarioSelecionado();
    
    if(usuarioSelecionado != null){
      int pkUsuario = usuarioSelecionado.getPkUsuario();
      String pkUsuarioStr = String.valueOf(pkUsuario);

      edtCodUsuario.setText(pkUsuarioStr);
      edtUsuario.setText(usuarioSelecionado.getNome());
    }
  }//GEN-LAST:event_btnBuscarUsuarioMouseClicked

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    carregarGrade();
  }//GEN-LAST:event_formWindowOpened

  private void btnGravarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarListaMouseClicked
    //crio uma lista de Usuario
    List<Usuario> listaSelecionados = new ArrayList<>();
    
    //percorro todas as linhas da grade
    for(int index=0; index < tblGrade.getRowCount(); index++){
      //pego o texto da coluna "Selecionado"
      String celula = tblGrade.getValueAt(index, 2).toString();
      
      //converto o texto da célula em boolean
      boolean selecionado = Boolean.parseBoolean(celula);
      
      //Se está selecionado adiciono na lista
      if (selecionado){
        //Pego o conteúdo da coluna "Nome" que contém o Usuario inteiro
        //A grade só sabe que o tipo de dado é Object que é uma
        //classe genérica, pode ser qualquer coisa
        Object objeto = tblGrade.getValueAt(index, 1);
        
        //para adicionar o objeto na lista forço o programa a ler 
        //a variável objeto como sendo do tipo Usuario atráves da expressão
        //(Usuario) objeto
        listaSelecionados.add((Usuario) objeto);
      }
    }
    
    for(Usuario usu: listaSelecionados){
      JOptionPane.showMessageDialog(null, usu.getNome());
    }
  }//GEN-LAST:event_btnGravarListaMouseClicked

  private void btnUsuarioLogadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioLogadoMouseClicked
    Usuario usu = UsuarioLogado.getUsuarioLogado();
    JOptionPane.showMessageDialog(null, usu);
    
  }//GEN-LAST:event_btnUsuarioLogadoMouseClicked

  
  public void carregarGrade(){
    //Pega o modelo da grade com suas colunas 
    DefaultTableModel modeloTabela = (DefaultTableModel) tblGrade.getModel();

    //Limpa a grade setando o número de linhas para zero
    modeloTabela.setNumRows(0);
    
    //consultar o banco de dados
    UsuarioController controller = new UsuarioController();
    
    //passar os filtros pro método consultar
    List<Usuario> listaUsuarios = controller.consultar(0, "");
    
    //preencher a grade
    for(Usuario usu: listaUsuarios){
      Object[] linha = {
        usu.getPkUsuario(),  //coluna 0
        usu, //coluna 1, guardei todo o Usuario
        false //coluna 2, todos desmarcados
      };
      
      modeloTabela.addRow(linha);
    }
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrCadastro dialog = new FrCadastro(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBuscarUsuario;
  private javax.swing.JButton btnGravarLista;
  private javax.swing.JButton btnUsuarioLogado;
  private javax.swing.JTextField edtCodUsuario;
  private javax.swing.JTextField edtUsuario;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblUsuario;
  private javax.swing.JPanel pnlPrincipal;
  private javax.swing.JTable tblGrade;
  // End of variables declaration//GEN-END:variables
}
