/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Usuario;
import model.UsuarioLogado;
import utils.Util;

/**
 *
 * @author iband
 */
public class FrLogin extends javax.swing.JFrame {

  /**
   * Creates new form FrLogin
   */
  public FrLogin() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlPrincipal = new javax.swing.JPanel();
    lblUsuario = new javax.swing.JLabel();
    lblSenha = new javax.swing.JLabel();
    edtUsuario = new javax.swing.JTextField();
    edtSenha = new javax.swing.JPasswordField();
    btnEntrar = new javax.swing.JButton();
    lblLogin = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    pnlPrincipal.setBackground(new java.awt.Color(153, 255, 204));
    pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    lblUsuario.setText("Usuário");
    pnlPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

    lblSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    lblSenha.setText("Senha");
    pnlPrincipal.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

    edtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    edtUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        edtUsuarioActionPerformed(evt);
      }
    });
    pnlPrincipal.add(edtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 254, -1));

    edtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    edtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        edtSenhaKeyPressed(evt);
      }
    });
    pnlPrincipal.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 254, -1));

    btnEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
    btnEntrar.setText("Entrar");
    btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnEntrarMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

    lblLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lblLogin.setText("LOGIN");
    pnlPrincipal.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, -1));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_login.png"))); // NOI18N
    pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void edtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtUsuarioActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_edtUsuarioActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
      logar();
    }//GEN-LAST:event_btnEntrarMouseClicked

  private void edtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSenhaKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      logar();
    }
  }//GEN-LAST:event_edtSenhaKeyPressed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // Define o ícone da janela
    this.setIconImage(Util.getIcone());
  }//GEN-LAST:event_formWindowOpened

  private boolean verificarCampos(){
    if(edtUsuario.getText().isEmpty()){
      JOptionPane.showMessageDialog(rootPane, "Usuário em branco");
      return false;
    }
    if(new String(edtSenha.getPassword()).isEmpty()){
      JOptionPane.showMessageDialog(rootPane, "Senha em branco");
      return false;
    }
    return true;
  }  
    
  private void logar() {
    if(!verificarCampos()){
      return;
    }
    //ler os campos
    String usuario = edtUsuario.getText();
    String senha = Util.calcularHash(new String(edtSenha.getPassword()));

    //consultar no banco de dados
    UsuarioController controller = new UsuarioController();

    Usuario usu = controller.autenticar(usuario, senha); 
    
    if (usu != null) {
      UsuarioLogado.setUsuarioLogado(usu);
      
      //Entra no sistema
      FrMenu telaMenu = new FrMenu();
      telaMenu.setVisible(true);  
      this.setVisible(false);
    } else {
      //Mensagem de usuário não encontrado
      JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado");
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrLogin().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEntrar;
  private javax.swing.JPasswordField edtSenha;
  private javax.swing.JTextField edtUsuario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel lblLogin;
  private javax.swing.JLabel lblSenha;
  private javax.swing.JLabel lblUsuario;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables
}
