/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import utils.Util;

/**
 *
 * @author iband
 */
public class FrMenu extends javax.swing.JFrame {

  /**
   * Creates new form FrMenu
   */
  public FrMenu() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlPrincipal = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    mnbPrincipal = new javax.swing.JMenuBar();
    mnCadastros = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    miUsuario = new javax.swing.JMenuItem();
    miSair = new javax.swing.JMenuItem();
    mnConsultas = new javax.swing.JMenu();
    miConUsuarios = new javax.swing.JMenuItem();
    miConOutro = new javax.swing.JMenuItem();
    mnSobre = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Menu - Projeto POO");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    pnlPrincipal.setBackground(new java.awt.Color(51, 255, 51));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

    javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
    pnlPrincipal.setLayout(pnlPrincipalLayout);
    pnlPrincipalLayout.setHorizontalGroup(
      pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
        .addGap(101, 101, 101)
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(89, 89, 89))
    );
    pnlPrincipalLayout.setVerticalGroup(
      pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlPrincipalLayout.createSequentialGroup()
        .addGap(56, 56, 56)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
        .addContainerGap(40, Short.MAX_VALUE))
    );

    mnCadastros.setText("Cadastros");

    jMenuItem1.setText("Usuário");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    mnCadastros.add(jMenuItem1);

    miUsuario.setText("???");
    mnCadastros.add(miUsuario);

    miSair.setText("Sair");
    miSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miSairActionPerformed(evt);
      }
    });
    mnCadastros.add(miSair);

    mnbPrincipal.add(mnCadastros);

    mnConsultas.setText("Consultas");

    miConUsuarios.setText("Usuários");
    miConUsuarios.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miConUsuariosActionPerformed(evt);
      }
    });
    mnConsultas.add(miConUsuarios);

    miConOutro.setText("???");
    mnConsultas.add(miConOutro);

    mnbPrincipal.add(mnConsultas);

    mnSobre.setText("Sobre");
    mnbPrincipal.add(mnSobre);

    setJMenuBar(mnbPrincipal);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    FrCadUsuario telaCadUsuario = new FrCadUsuario(this, rootPaneCheckingEnabled);
    telaCadUsuario.setVisible(true);
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void miConUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConUsuariosActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miConUsuariosActionPerformed

  private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
    this.dispose();
  }//GEN-LAST:event_miSairActionPerformed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // Define o ícone da janela
    this.setIconImage(Util.getIcone());
  }//GEN-LAST:event_formWindowOpened

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem miConOutro;
  private javax.swing.JMenuItem miConUsuarios;
  private javax.swing.JMenuItem miSair;
  private javax.swing.JMenuItem miUsuario;
  private javax.swing.JMenu mnCadastros;
  private javax.swing.JMenu mnConsultas;
  private javax.swing.JMenu mnSobre;
  private javax.swing.JMenuBar mnbPrincipal;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables
}
