/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author iband
 */
public class FrPreencherCombo extends javax.swing.JDialog {
  
  private Usuario usuarioSelecionado;
  
  /**
   * Creates new form FrTeste2
   */
  public FrPreencherCombo(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }
  
  public Usuario getUsuarioSelecionado(){
    return usuarioSelecionado;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlPrincipal = new javax.swing.JPanel();
    cbxUsuarios = new javax.swing.JComboBox<>();
    btnAddUsuarios = new javax.swing.JButton();
    btnLerCampo = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    btnSelecionar = new javax.swing.JButton();
    btnVoltar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    pnlPrincipal.add(cbxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 173, -1));

    btnAddUsuarios.setText("Add Usuários na Combo");
    btnAddUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnAddUsuariosMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnAddUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

    btnLerCampo.setText("Ler Combo");
    btnLerCampo.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnLerCampoMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnLerCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

    jLabel1.setText("Exemplo de como adicionar Objetos dentro da ComboBox");
    pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

    jLabel2.setText("Selecione a ComboBox, abra as propriedades clicando com o botão direito");
    pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    jLabel3.setText("na aba \"Código\" altere a propriedade \"Parâmetros de Tipo\" e coloque a <SuaClasse>");
    pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

    btnSelecionar.setText("Selecionar");
    btnSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnSelecionarMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

    btnVoltar.setText("Voltar");
    btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnVoltarMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnAddUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUsuariosMouseClicked
    UsuarioController controller = new UsuarioController();
    //Consulto todos os usuários
    List<Usuario> lista = controller.consultar(0, "");

    //percorro a lisa de usuários
    for (Usuario usu : lista) {
      //para cada usuário eu adiciono ele na lista
      cbxUsuarios.addItem(usu);
      //O texto que irá aparecer dentro da ComboBox é o método toString() 
      //da classe Usuario
    }
  }//GEN-LAST:event_btnAddUsuariosMouseClicked

  private void btnLerCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLerCampoMouseClicked
    //pego o index do item selecionado na ComboBox
    int indexSelecionado = cbxUsuarios.getSelectedIndex();
    
    //com o index eu consigo pegar o objeto inteiro de dentro da ComboBox
    Usuario usu = cbxUsuarios.getItemAt(indexSelecionado);

    if (usu != null) {
      JOptionPane.showMessageDialog(null, "Nome:" + usu.getNome() + " \n Email: " + usu.getEmail());
    }

  }//GEN-LAST:event_btnLerCampoMouseClicked

  private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
    this.dispose();
  }//GEN-LAST:event_btnVoltarMouseClicked

  private void btnSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarMouseClicked
    int indexSelecionado = cbxUsuarios.getSelectedIndex();
    
    //com o index eu consigo pegar o objeto inteiro de dentro da ComboBox
    
    usuarioSelecionado = cbxUsuarios.getItemAt(indexSelecionado);
    
    this.dispose();
  }//GEN-LAST:event_btnSelecionarMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrPreencherCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrPreencherCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrPreencherCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrPreencherCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrPreencherCombo dialog = new FrPreencherCombo(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAddUsuarios;
  private javax.swing.JButton btnLerCampo;
  private javax.swing.JButton btnSelecionar;
  private javax.swing.JButton btnVoltar;
  private javax.swing.JComboBox<Usuario> cbxUsuarios;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables
}
