/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;
import utils.Util;

/**
 *
 * @author iband
 */
public class FrSobre extends javax.swing.JDialog {

  /**
   * Creates new form FrSobre
   */
  public FrSobre(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlPrincipal = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    btnVoltar = new javax.swing.JButton();
    btnGitHub = new javax.swing.JButton();
    btnLinkedIn = new javax.swing.JButton();
    lblInfo3 = new javax.swing.JLabel();
    lblInfo1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    lblInfo2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Sobre - Projeto POO");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    pnlPrincipal.setBackground(new java.awt.Color(204, 255, 153));
    pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lblTitulo.setText("Sobre");
    pnlPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

    btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
    btnVoltar.setText("Voltar");
    btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnVoltarMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

    btnGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github.png"))); // NOI18N
    btnGitHub.setText("GitHub");
    btnGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnGitHubMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnGitHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

    btnLinkedIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/linkedin.png"))); // NOI18N
    btnLinkedIn.setText("LinkedIn");
    btnLinkedIn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnLinkedInMouseClicked(evt);
      }
    });
    pnlPrincipal.add(btnLinkedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

    lblInfo3.setText("Data: 08/09/2025");
    pnlPrincipal.add(lblInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

    lblInfo1.setText("Versão: 1.0.0");
    pnlPrincipal.add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

    jLabel3.setText("Versão: 1.0.0");
    pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

    lblInfo2.setText("Autor: Igor Bandasz");
    pnlPrincipal.add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_medio.png"))); // NOI18N
    pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 70, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setIconImage(Util.getIcone());
  }//GEN-LAST:event_formWindowOpened

  private void btnGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGitHubMouseClicked
    try {
      //Pego os dados do computador
      Desktop desktop = Desktop.getDesktop();
      
      //monto o caminho que quero acessar, seu github
      URI uri = new URI("https://github.com/igorbandasz");
      
      //mando o navegador abrir a URI
      desktop.browse(uri);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e);
    }
  }//GEN-LAST:event_btnGitHubMouseClicked

  private void btnLinkedInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinkedInMouseClicked
    try {
      //Pego os dados do computador
      Desktop desktop = Desktop.getDesktop();
      
      //monto o caminho que quero acessar, seu github
      URI uri = new URI("https://www.linkedin.com/in/igor-bandasz");
      
      //mando o navegador abrir a URI
      desktop.browse(uri);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e);
    }
  }//GEN-LAST:event_btnLinkedInMouseClicked

  private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
    this.dispose();
  }//GEN-LAST:event_btnVoltarMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrSobre dialog = new FrSobre(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGitHub;
  private javax.swing.JButton btnLinkedIn;
  private javax.swing.JButton btnVoltar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel lblInfo1;
  private javax.swing.JLabel lblInfo2;
  private javax.swing.JLabel lblInfo3;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JPanel pnlPrincipal;
  // End of variables declaration//GEN-END:variables
}
